### ISSUE TITLE
Management of the 'quit' command

### ISSUE THREAD

**Issue by rchastain** [Dany1962/BeLL#2]
Hello Daniel!
When I do a tournament with Cute Chess, I have a warning saying that Cute Chess had to terminate BeLL process. I believe that there is a problem in the 'quit' command management. You see the problem if you start BeLL manually: you have to enter 'quit' twice to close the program. I had a look into the code but as I am not a C expert, I didn't see the solution.
I forgot to say that I am under Windows. By the way, I got warnings from Windows Defender when I cloned your repository.
Regards.
Roland

**Comment by Dany1962** [comment]
Hello Roland
Thanks to pointed that for me . Didn't notice any problems under aréna, strange...
I'll have a look at this 
Bests 
Dany

**Comment by rchastain** [comment]
OK, thank you.
